### PR TITLE
function id_from_list_dict added

### PR DESCRIPTION
**Pull request by juanpabloaj**
* get_user_id method added to Users class
* refactor: get_user_id and get_channel_id use the same lines.

### CODE REVIEW

**Comment by os** [comment]
@juanpabloaj Thank you for this. Two things... Can you rename **id_from_list_dict** with something like **get_item_id_by_name**? Also, can you rebase to clean up your changes so **get_user_id** will be added after that function? Therefore, it will not appear in commit history twice.

**Comment by juanpabloaj** [comment]
ok, I renamed id_from_list_dict function.

but I don't understand the second thing, If I make a rebase, I need make a force push ? to overwrite this branch

and, I need make this rebase and force push : 

     git checkout id_from_list_dict
     git rebase master
     git rebase master id_from_list_dict
     git push -f juanpabloaj id_from_list_dict

... ?

**Comment by os** [comment]
What I’m trying to say is that the pull request should only include what matters. You can change a variable name hundreds of times and have individual commits for each. But it’s the latest version only that matters, not the changes you’ve made in between. So instead of a history like:

* Add get_channel_id function.
* Add get_item_id_by_name function.
* Rewrite get_channel_id using get_item_id_by_name.

It’s better to have:

* Add get_item_by_name function.
* Add get_channel_id function.

**Comment by juanpabloaj** [comment]
but, this sequence is the history of development

* Add get_user_id function with very similar code to get_channel_id
* Add get_item_id_by_name function, refactor because get_channel_id and get_user_id are very similar 
* rename get_channel_id to  get_item_id_by_name.

if you prefer I can open other pull request, with two commits

* Add get_item_by_name function.
* Add get_channel_id function.

or all changes in one single commit

**Comment by juanpabloaj** [comment]
reorder commits in pull request #21

**Pull request closed without merging**
