### PR TITLE
Handle 429 Retry-After Errors

### PR DESCRIPTION
**Pull request by chazchazchaz**
From https://api.slack.com/docs/rate-limits
> The Slack API and all integrations are subject to rate limiting.
>
>If you go over these limits when using our HTTP based APIs, including Incoming Webhooks, Slack will start returning a HTTP 429 Too Many Requests error, a JSON object containing the number of calls you have been making, and a Retry-After header containing the number of seconds until you can retry.

This will correctly raise a UserWarning for the 429 error, and give the retry delay in seconds to be used in `args[1]`, so that a script can sleep, then retry/continue.

This can be handled as shown in the `except UserWarning` area example:

```
try:
    response = slack.chat.post_message(channel, message)
except UserWarning as e:
    print('Error:', e)
    time.sleep(e.args[1])
    continue    # retrying can also be written here
except Exception as e:
    print('Error:', e)
    exit(1)
```

related: https://github.com/os/slacker/pull/40

### CODE REVIEW

**Comment by psykzz** [comment]
Request already raised an exception, Wouldn't it make sense to just handle that error as you would normally?

Right now you are making the way to handle 429 unique to slacker whereas before it would've been the same across all requests implementations.

**Comment by chazchazchaz** [comment]
In the current state, the status code and all other information, except for the response text, is swallowed on line 59/65. If there is a better practice to do this, I am very open to suggestions. 429 errors are not necessarily a reason for an application to stop, but instead slow down the requests, and retry the previous one.

'response = Response(response.text)`

**Comment by os** [comment]
Hi @chazchazchaz. Wouldn't `response.raise_for_status()` give you an `HTTPError` (see https://github.com/kennethreitz/requests/blob/7322a09379565bbeba9bb40000b41eab8856352e/requests/models.py#L868) already?

**Comment by chazchazchaz** [comment]
Hi @os, I re-ran my test code to cause the issue and now get these exceptions, as you noted, which can be handled. Thanks for following up!

('Error posting message:', HTTPError(u'429 Client Error: Too Many Requests for url: https://slack.com/api/chat.postMessage?token=xoxp-[snipped]',))

**Pull request closed without merging**
