### PR TITLE
Blocks Support (squashed commits from #152)

### PR DESCRIPTION
**Pull request by symroe**
This PR is a duplicate of #152 but with a single commit rather than 4. 

As Slack is pushing blocks as the default for complex messages, this PR is important for anyone reading the current docs and wanting to use Slacker with them.

### CODE REVIEW

**Comment by botzill** [comment]
OK, any idea who is responsable to merge this PR? Would be great to have this feature added.

**Comment by botzill** [comment]
Hi.

Still no one here to merge this PR?

**Comment by symroe** [comment]
I've been using it for about a month now, and it's working fine.

Low risk merge IMHO.

**Comment by botzill** [comment]
I don't have the permission to merge.

**Comment by senpay** [comment]
@symroe Hey! I decided to fork slacker for now and publish it under some other name in pypi. Please feel free to suggest your PR there - I will do my best to merge it timely and release (ETA~7 days)

**Comment by senpay** [comment]
@os Hey! I am forking and will maintain the release of slacker for now under another name. As soon as you can get back to supporting slacker  - ping me, we will back merge all what you think relevant.

**Comment by os** [comment]
Thanks. There are many unrelated commits here so it's difficult to merge it as-is. Should we close this and create separate PRs for each change?

**Comment by symroe** [comment]
The unrelated ones are because I gave up on this PR after months of being ignored, and moved to the forked repo…

Happy for you to take it from here if you want to carry on supporting this code base, but I've moved my dependencies to the other fork 🤷‍♂

**Pull request closed without merging**
