### PR TITLE
ensure attachments are json-encoded.

### PR DESCRIPTION
**Pull request by abelsonlive**
RE: https://github.com/slackhq/node-slack-client/issues/12#issuecomment-104754740

### CODE REVIEW

**Comment by abelsonlive** [comment]
also RE: https://github.com/os/slacker/issues/30

**Comment by os** [comment]
`isinstance(attachments, basestring)` would raise a NameError in Python 3 because there is no such type anymore.

**Comment by abelsonlive** [comment]
I changed it to an affirmative test for `list`

**Comment by os** [comment]
Great, thanks!

**Comment by os** [comment]
Now available in v0.6.1.

**Pull request merged**
